baseurl = "https://www.robinbentley.com/"
title = "Robin Bentley - Senior Developer"
languageCode = "en-gb"

[params]
  author = "Robin Bentley"
  description = "Manchester based senior developer. Currently working with Node, React and Typescript"

[social]
  github = "https://github.com/robinbentley"
  linkedin = "https://www.linkedin.com/in/robin-bentley"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[Taxonomies]
